- name: Clone chirpstack docker compose
  git:
    repo: https://github.com/lhc/chirpstack-docker
    dest: /home/{{ansible_user}}/chirpstack
    clone: yes
    update: yes
    force: yes
    version: master

- name: Copy Chirpstack gateway Bridge config
  copy:
    src: files/chirpstack-gateway-bridge.toml
    dest: /home/{{ansible_user}}//chirpstack/configuration/chirpstack-gateway-bridge/


- name: Tear Downs Docker Compose stack
  community.docker.docker_compose:
    project_src: "/home/{{ansible_user}}/chirpstack"
    files: docker-compose.yml
    state: absent        

#The parameter below are used to connect with remote postgres and values are envrypted located in secrets.yml
- name: Run docker-compose passing arguments
  ansible.builtin.shell:
    cmd: >
      SERVER_BROKER_HOST="{{broker.host}}"
      SERVER_BROKER_USER="{{broker.user}}"
      SERVER_BROKER_PASS="{{broker.password}}"
      SERVER_BROKER_TYPE="rabbitmq"
      docker-compose up -d
    chdir: "/home/{{ansible_user}}/chirpstack"


